#!/usr/bin/env bash
# Stub für 'nft'. Protokolliert den Aufruf und verhält sich so, wie es
# der Testfall über STUB_<KOMMANDO>_RC / _OUT vorgibt.
printf '%s %s\n' "nft" "$*" >>"${STUB_LOG:-/dev/null}"
_var="STUB_NFT_OUT"
[[ -n "${!_var:-}" ]] && printf '%s\n' "${!_var}"
_rc="STUB_NFT_RC"
exit "${!_rc:-0}"
