#!/usr/bin/env bash
# Stub für 'ss'. Protokolliert den Aufruf und verhält sich so, wie es
# der Testfall über STUB_<KOMMANDO>_RC / _OUT vorgibt.
printf '%s %s\n' "ss" "$*" >>"${STUB_LOG:-/dev/null}"
_var="STUB_SS_OUT"
[[ -n "${!_var:-}" ]] && printf '%s\n' "${!_var}"
_rc="STUB_SS_RC"
exit "${!_rc:-0}"
