#!/usr/bin/env bash
# Stub für 'sshd'. Protokolliert den Aufruf und verhält sich so, wie es
# der Testfall über STUB_<KOMMANDO>_RC / _OUT vorgibt.
printf '%s %s\n' "sshd" "$*" >>"${STUB_LOG:-/dev/null}"
_var="STUB_SSHD_OUT"
[[ -n "${!_var:-}" ]] && printf '%s\n' "${!_var}"
_rc="STUB_SSHD_RC"
exit "${!_rc:-0}"
